# Generated by Django 5.0.6 on 2024-06-23 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4)),
                ('number', models.CharField(max_length=6)),
                ('slug', models.CharField(max_length=11, null=True, unique=True)),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='person', to='registry.person')),
            ],
        ),
    ]
